version: '1.0'
services:
  nestjs-fastify-template:
    image: nfst/nestjs-fastify-template
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-fastify-template-server
    environment:
      SNOWFLAKE_MACHINE_ID: '1'
    volumes:
      - ./.env.prod:/usr/src/app/.env.prod
    ports:
      - 8080:8080
    restart: unless-stopped
