version: '1.0'
services:
  nestjs-fastify-template:
    image: nfst/nestjs-fastify-template
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-fastify-template-server
    environment:
      SNOWFLAKE_MACHINE_ID: '1'
    volumes:
      - ./.env.prod:/usr/src/app/.env.prod
    ports:
      - 18080:8080
    networks:
      - nestjs-fastify_default
    restart: unless-stopped
  mysql:
    container_name: mysql8
    image: 'mysql:8.0.33'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: r1234567890
      MYSQL_DATABASE: nfst
      MYSQL_USER: root
      MYSQL_PASSWORD: m123456789
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - 3387:3306
    networks:
      - nestjs-fastify_default
    restart: unless-stopped
  redis:
    container_name: redis
    image: 'redis:alpine'
    command: redis-server --save "" --appendonly "yes"
    networks:
      - nestjs-fastify_default
    restart: unless-stopped
    ports:
      - 6379:6379
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  nestjs-fastify_default:
    external: true

volumes:
  mysql-data:
